prediction_model_name: deepseek-v4-flash
model:
  model_name: openai/deepseek-v4-flash
  cost_tracking: ignore_errors
  model_kwargs:
    api_base: https://dashscope.aliyuncs.com/compatible-mode/v1
    drop_params: true
    temperature: 0.0
    max_tokens: 16384
    timeout: 300
    extra_body:
      enable_thinking: false
    api_key: $DASHSCOPE_API_KEY
  model_class: litellm
_model_source: dashscope
environment:
  run_args:
  - --rm
  - --cap-add=NET_ADMIN
